In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Upload data

Here is a summary of the dataset in points:

<font color = "cyan"> Dataset Overview </font>

-  Decathlon dataset with 41 athletes (rows).
-  In the original file, athletes are classified into 4 classes, but for this exercise, we are working with 3 labeled classes: 1, 2, and 3.
-  One qualitative column "Classe" containing the label for each athlete.
     
<font color = "cyan"> Variables </font>
-  10 quantitative variables (athletes' performances).
-  2 quantitative variables (Classement and Points).
-  One qualitative variable: competition (2004 Olympic Games or Decastar).
     
<font color = "cyan"> Scope of the Exercice </font>
-  Focuses only on classes 1, 2 and 3
-  Analyzes 10 athletes’ performances variables.

<font color = "cyan"> Filtered Dataset for study </font>
-  Rows: 38 (classes 1, 2 and 3).
-  Columns: 10 (athletes’ performances).


In [ ]:
# Import des données
data = pd.read_csv('/content/drive/MyDrive/e-business & Big Data/Machine Learning/Mini Project/data/decathlon.csv',sep=";")
data

Unnamed: 0   100m  Longueur  Poids  Hauteur   400m  110m H  Disque  \
0         Macey  10.89      7.47  15.73     2.15  48.97   14.56   48.34   
1       Warners  10.62      7.74  14.48     1.97  47.97   14.01   43.73   
2     Zsivoczky  10.91      7.14  15.31     2.12  49.40   14.95   45.62   
3         Hernu  10.97      7.19  14.65     2.03  48.73   14.25   44.72   
4          Nool  10.80      7.53  14.26     1.88  48.81   14.80   42.05   
5       Bernard  10.69      7.48  14.80     2.12  49.13   14.17   44.75   
6      Schwarzl  10.98      7.49  14.01     1.94  49.76   14.25   42.43   
7     Pogorelov  10.95      7.31  15.10     2.06  50.79   14.21   44.60   
8    Schoenbeck  10.90      7.30  14.77     1.88  50.30   14.34   44.41   
9        Barras  11.14      6.99  14.91     1.94  49.41   14.37   44.83   
10        Smith  10.85      6.81  15.24     1.91  49.27   14.01   49.02   
11    Averyanov  10.55      7.34  14.44     1.94  49.72   14.39   39.88   
12     Ojaniemi  10.68      7.50  14.97     1.94  49.12   15.01   40.35   
13      Smirnov  10.89      7.07  13.88     1.94  49.11   14.77   42.47   
14           Qi  11.06      7.34  13.55     1.97  49.65   14.78   45.13   
15        Drews  10.87      7.38  13.07     1.88  48.51   14.01   40.11   
16  Parkhomenko  11.14      6.61  15.69     2.03  51.04   14.88   41.90   
17        Terek  10.92      6.94  15.15     1.94  49.56   15.12   45.62   
18        Gomez  11.08      7.26  14.57     1.85  48.61   14.41   40.95   
19         Turi  11.08      6.91  13.62     2.03  51.67   14.26   39.83   
20      Lorenzo  11.10      7.03  13.22     1.85  49.34   15.38   40.22   
21    Karlivans  11.33      7.26  13.30     1.97  50.54   14.98   43.34   
22  Korkizoglou  10.86      7.07  14.81     1.94  51.16   14.96   46.07   
23        Uldal  11.23      6.99  13.53     1.85  50.95   15.09   43.01   
24      Casarsa  11.36      6.68  14.92     1.94  53.20   15.39   48.66   
25       SEBRLE  11.04      7.58  14.83     2.07  49.81   14.69   43.75   
26         CLAY  10.76      7.40  14.26     1.86  49.37   14.05   50.72   
27       KARPOV  11.02      7.30  14.77     2.04  48.37   14.09   48.95   
28      BERNARD  11.02      7.23  14.25     1.92  48.93   14.99   40.87   
29       YURKOV  11.34      7.09  15.19     2.10  50.42   15.31   46.26   
30      WARNERS  11.11      7.60  14.31     1.98  48.68   14.23   41.10   
31    ZSIVOCZKY  11.13      7.30  13.48     2.01  48.62   14.17   45.67   
32     McMULLEN  10.83      7.31  13.76     2.13  49.91   14.38   44.41   
33    MARTINEAU  11.64      6.81  14.57     1.95  50.14   14.93   47.60   
34        HERNU  11.37      7.56  14.41     1.86  51.10   15.06   44.99   
35       BARRAS  11.33      6.97  14.09     1.95  49.48   14.48   42.10   
36         NOOL  11.33      7.27  12.68     1.98  49.20   15.29   37.92   
37  BOURGUIGNON  11.36      6.80  13.46     1.86  51.16   15.67   40.49   

    Perche  Javelot   1500m  Classement  Points Competition  Classe  
0     4.40    58.46  265.42           4    8414          JO       1  
1     4.90    55.39  278.05           5    8343          JO       2  
2     4.70    63.45  269.54           6    8287          JO       1  
3     4.80    57.76  264.35           7    8237          JO       1  
4     5.40    61.33  276.33           8    8235          JO       2  
5     4.40    55.27  276.31           9    8225          JO       1  
6     5.10    56.32  273.56          10    8102          JO       2  
7     5.00    53.45  287.63          11    8084          JO       2  
8     5.00    60.89  278.82          12    8077          JO       2  
9     4.60    64.55  267.09          13    8067          JO       1  
10    4.20    61.52  272.74          14    8023          JO       1  
11    4.80    54.51  271.02          15    8021          JO       2  
12    4.60    59.26  275.71          16    8006          JO       1  
13    4.70    60.88  263.31          17    7993          JO       1  
14    4.50    60.79  272.63  

In [ ]:
data.describe()

100m   Longueur      Poids    Hauteur       400m     110m H  \
count  38.000000  38.000000  38.000000  38.000000  38.000000  38.000000   
mean   11.029737   7.211842  14.369474   1.967895  49.734474  14.649737   
std     0.240927   0.274471   0.744783   0.085934   1.078687   0.461797   
min    10.550000   6.610000  12.680000   1.850000  47.970000  14.010000   
25%    10.875000   7.000000  13.790000   1.912500  49.005000  14.250000   
50%    11.020000   7.265000  14.460000   1.945000  49.445000  14.625000   
75%    11.140000   7.395000  14.890000   2.030000  50.390000  14.987500   
max    11.640000   7.740000  15.730000   2.150000  53.200000  15.670000   

          Disque     Perche    Javelot       1500m  Classement       Points  \
count  38.000000  38.000000  38.000000   38.000000   38.000000    38.000000   
mean   43.865000   4.756842  57.768684  278.944737   12.921053  7941.631579   
std     3.039891   0.284197   4.139714   12.125119    7.666641   263.313031   
min    37.920000   4.200000  50.310000  262.100000    1.000000  7313.000000   
25%    41.300000   4.500000  54.827500  270.030000    7.000000  7750.250000   
50%    44.080000   4.760000  58.060000  277.170000   11.500000  8005.000000   
75%    45.620000   4.920000  60.857500  285.100000   18.750000  8095.250000   
max    50.720000   5.400000  65.820000  317.000000   28.000000  8414.000000   

          Classe  
count  38.000000  
mean    1.921053  
std     0.818092  
min     1.000000  
25%     1.000000  
50%     2.000000  
75%     3.000000  
max     3.000000

In [ ]:
X = data.values[:,1:-4]
Y = data[data.keys()[-1]].values
print(X.shape,Y.shape)
print(X)

(38, 10) (38,)
[[10.89 7.47 15.73 2.15 48.97 14.56 48.34 4.4 58.46 265.42]
 [10.62 7.74 14.48 1.97 47.97 14.01 43.73 4.9 55.39 278.05]
 [10.91 7.14 15.31 2.12 49.4 14.95 45.62 4.7 63.45 269.54]
 [10.97 7.19 14.65 2.03 48.73 14.25 44.72 4.8 57.76 264.35]
 [10.8 7.53 14.26 1.88 48.81 14.8 42.05 5.4 61.33 276.33]
 [10.69 7.48 14.8 2.12 49.13 14.17 44.75 4.4 55.27 276.31]
 [10.98 7.49 14.01 1.94 49.76 14.25 42.43 5.1 56.32 273.56]
 [10.95 7.31 15.1 2.06 50.79 14.21 44.6 5.0 53.45 287.63]
 [10.9 7.3 14.77 1.88 50.3 14.34 44.41 5.0 60.89 278.82]
 [11.14 6.99 14.91 1.94 49.41 14.37 44.83 4.6 64.55 267.09]
 [10.85 6.81 15.24 1.91 49.27 14.01 49.02 4.2 61.52 272.74]
 [10.55 7.34 14.44 1.94 49.72 14.39 39.88 4.8 54.51 271.02]
 [10.68 7.5 14.97 1.94 49.12 15.01 40.35 4.6 59.26 275.71]
 [10.89 7.07 13.88 1.94 49.11 14.77 42.47 4.7 60.88 263.31]
 [11.06 7.34 13.55 1.97 49.65 14.78 45.13 4.5 60.79 272.63]
 [10.87 7.38 13.07 1.88 48.51 14.01 40.11 5.0 51.53 274.21]
 [11.14 6.61 15.69 2.03 51.04 14.88